export enum enUS {
  CheckPackageNotInstalled = 'Check package not installed: {{pkg}}',
  CheckPathInvalid = 'Local check module not found or invalid: {{path}}',
  CheckTimeout = 'Check timed out after {{seconds}}s',
  ErrorBullet = '  ✖ ',
  InvalidCheckExport = 'Invalid check export from {{pkg}}: expected default.name === "{{name}}"',
  NoChecksConfigured = 'No checks configured. Install @mayjournal/fitness-checks or add .fitnessrc with a checks list.',
  PleaseFix = 'Please fix these items:',
  ResolvingChecks = 'Resolving checks...',
  RunningCheck = '  → {{name}}',
  RunningChecks = 'Running checks:',
  StatusFailed = 'failed',
  StatusPassed = 'passed',
  TableCheck = 'Check',
  TableFiles = 'Files',
  TableStatus = 'Status',
  TableTime = 'Time',
  TotalLine = 'Total: {{success}} succeeded, {{failure}} failed, {{files}} files in {{ms}}ms',
  UnknownCheckPrefix = 'Unknown check: ',
  UnknownCheckSpecNone = '(none)',
}
