#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

msg="$(cat "$1")"
go/bin/fitness --check=semantic-commit --message="$msg"
go/bin/fitness --check=plan-trailer --message="$msg"
