/** @typedef {{ name: string, dir?: string, sizes?: { tarball: number, unpacked: number }, publint?: { ok: boolean, errors: number, warnings: number }, error?: string, attw?: { ok: boolean, summary?: string, error?: string } }} AuditRow */

/** @param {number} bytes */
export function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KiB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MiB`;
}

export const RUNNER_PACKAGE = '@mayjournal/fitness';
/** Default max npm pack tarball bytes for @mayjournal/fitness (~24 KiB; baseline ~20 KiB). */
export const DEFAULT_RUNNER_MAX_TARBALL = 24 * 1024;

/**
 * @param {AuditRow[]} rows
 * @param {{ runnerMaxTarball?: number }} [opts]
 * @returns {{ ok: boolean, runnerTarball?: number, limit: number, message?: string }}
 */
export function checkRunnerTarballGate(rows, opts = {}) {
  const limit = opts.runnerMaxTarball ?? DEFAULT_RUNNER_MAX_TARBALL;
  const runner = rows.find((r) => r.name === RUNNER_PACKAGE);
  if (!runner?.sizes) {
    return { limit, message: 'Runner package missing from audit results', ok: false };
  }
  const { tarball } = runner.sizes;
  if (tarball > limit) {
    return {
      limit,
      message: `${RUNNER_PACKAGE} tarball ${formatBytes(tarball)} exceeds limit ${formatBytes(limit)}`,
      ok: false,
      runnerTarball: tarball,
    };
  }
  return { limit, ok: true, runnerTarball: tarball };
}

/**
 * @param {AuditRow[]} rows
 * @param {{ gate?: { ok: boolean, message?: string }, attwRows?: { name: string, ok: boolean, summary?: string }[] }} [extra]
 */
export function formatMarkdownReport(rows, extra = {}) {
  const sorted = [...rows].sort((a, b) => (b.sizes?.tarball ?? 0) - (a.sizes?.tarball ?? 0));
  const total = sorted.reduce((n, r) => n + (r.sizes?.tarball ?? 0), 0);
  const publintFails = sorted.filter((r) => r.publint && !r.publint.ok);
  const packErrors = sorted.filter((r) => r.error);

  const lines = [
    '## Publish audit',
    '',
    'Tarball sizes from `npm pack --dry-run` (compressed `.tgz` bytes).',
    '',
    '| Package | Tarball | Unpacked | Publint |',
    '| --- | ---: | ---: | --- |',
  ];

  for (const row of sorted) {
    if (row.error) {
      lines.push(`| ${row.name} | — | — | error |`);
      continue;
    }
    const lint = row.publint?.ok ? 'ok' : `${row.publint?.errors ?? '?'} err`;
    lines.push(
      `| ${row.name} | ${formatBytes(row.sizes.tarball)} | ${formatBytes(row.sizes.unpacked)} | ${lint} |`
    );
  }

  lines.push('', `**Total (15 packages):** ${formatBytes(total)}`);

  if (extra.gate) {
    lines.push('');
    if (extra.gate.ok) {
      lines.push(
        `**Runner size gate:** ok (${formatBytes(extra.gate.runnerTarball ?? 0)} ≤ ${formatBytes(extra.gate.limit)})`
      );
    } else {
      lines.push(`**Runner size gate:** failed — ${extra.gate.message}`);
    }
  }

  if (publintFails.length) {
    lines.push('', '### Publint failures', '');
    for (const row of publintFails) {
      lines.push(
        `<details><summary>${row.name}</summary>\n\n\`\`\`\n${row.publint.output}\n\`\`\`\n</details>`,
        ''
      );
    }
  }

  if (packErrors.length) {
    lines.push('', '### Pack errors', '');
    for (const row of packErrors) {
      lines.push(`- ${row.name}: ${row.error}`);
    }
  }

  const attwRows = extra.attwRows?.filter((a) => !a.skipped) ?? [];
  const attwSkipped = extra.attwRows?.filter((a) => a.skipped) ?? [];
  if (attwSkipped.length) {
    lines.push(
      '',
      '_attw (Are The Types Wrong) skipped: CLI currently crashes in CI (`Cannot read properties of undefined`). Advisory only; re-enable when upstream fixes._'
    );
  }
  if (attwRows.length) {
    lines.push('', '### Are The Types Wrong (attw)', '');
    for (const a of attwRows) {
      lines.push(a.ok ? `- ${a.name}: ok` : `- ${a.name}: issues`);
      if (!a.ok && a.summary) lines.push('', '```', a.summary.trim(), '```', '');
    }
  }

  lines.push('', '_Generated by `npm run audit:publish`._');
  return lines.join('\n');
}
