export enum enUS {
  ErrorBullet = '  ✖ ',
  PleaseFix = 'Please fix these items:',
  ResolvingChecks = 'Resolving checks...',
  RunningCheck = '  → {{name}}',
  RunningChecks = 'Running checks:',
  StatusFailed = 'failed',
  StatusPassed = 'passed',
  TableCheck = 'Check',
  TableFiles = 'Files',
  TableStatus = 'Status',
  TableTime = 'Time',
  TotalLine = 'Total: {{success}} succeeded, {{failure}} failed, {{files}} files in {{ms}}ms',
  UnknownCheckPrefix = 'Unknown check: ',
  UnknownCheckSpecNone = '(none)',
}
